volumes:
  minio_data:
  pg_data:

services:
  docx_report_generator:
    build: ./docx_report_generator/
    env_file: .env
    depends_on:
      - db
      - s3_minio
  db:
    image: postgres:17.4
    container_name: db
    environment:
      POSTGRES_PASSWORD: 643941
    ports:
      - 5444:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./campaign_stats.sql:/docker-entrypoint-initdb.d/campaign_stats.sql
  s3_minio:
    image: quay.io/minio/minio
    container_name: storage
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: onecadmin
      MINIO_ROOT_PASSWORD: onecadmin
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data